[project]
name = "time"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.16.0",
    "pydantic>=2.11.9",
    "tzlocal>=5.3.1",
]

